# Generated by Django 5.0.7 on 2024-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=13)),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('category', models.TextField(choices=[('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Comics', 'Comics'), ('Crime', 'Crime'), ('Novel', 'Novel')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='book_images/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
