# Generated by Django 5.0.7 on 2024-07-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='genre',
        ),
    ]
