# Generated by Django 5.0.7 on 2024-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_category_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
