# Generated by Django 5.0.7 on 2024-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=300),
        ),
    ]
